services:
  - type: web
    name: warps-makex
    env: node
    plan: free
    buildCommand: 'npm install --legacy-peer-deps'
    startCommand: 'npm start'
    envVars:
      - key: API_PROVIDER
        value: "https://api.multiversx.com"
      - key: CHAIN
        value: "mainnet"
      - key: SECURE_TOKEN
        sync: false
      - key: REWARD_TOKEN
        value: "REWARD-cf6eac"
      - key: TREASURY_WALLET
        value: "erd1t2r97zcjg8uvf0e9nk4psj2kvg27mph9kq5xls6xtnyg2aemp8hszcmn8f"
    autoDeploy: true
    region: frankfurt
